---
driver:
  name: gce
  project: winter-clone-191701
  zone: us-east1-b
  email: raghudevops25@gmail.com
   

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

transport:
  username: ec2-user
  ssh_key:
        - ~/devops.pem

verifier:
  name: inspec

platforms:
  - name: centos-7
    driver:
      #image_project: winter-clone-191701
      image_name: mycentos7

suites:
  - name: default
    run_list:
      - recipe[web::install]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
